// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc696.RobotBuilderredemption.subsystems;
import org.usfirst.frc696.RobotBuilderredemption.RobotMap;
import org.usfirst.frc696.RobotBuilderredemption.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class LEDs extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalOutput red = RobotMap.lEDsred;
    DigitalOutput green = RobotMap.lEDsgreen;
    DigitalOutput blue = RobotMap.lEDsblue;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        
        red.setPWMRate(15000);
        green.setPWMRate(15000);
        blue.setPWMRate(15000);
        red.enablePWM(1.0);
        green.enablePWM(0.0);
        blue.enablePWM(0.5);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void setleds(double _red, double _green, double _blue){
        red.updateDutyCycle(_red);
        green.updateDutyCycle(_green);
        blue.updateDutyCycle(_blue);
    }
}
