// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc696.RobotBuilderredemption.subsystems;
import org.usfirst.frc696.RobotBuilderredemption.RobotMap;
import org.usfirst.frc696.RobotBuilderredemption.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class shooter extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController choochooRight = RobotMap.shooterchoochooRight;
    SpeedController choochooLeft = RobotMap.shooterchoochooLeft;
    DigitalInput choochooLimitSwitchLeft = RobotMap.shooterchoochooLimitSwitchLeft;
    Solenoid ejectSolenoid = RobotMap.shooterejectSolenoid;
    DigitalInput choochooLimitSwitchRight = RobotMap.shooterchoochooLimitSwitchRight;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void extendPiston(){
        ejectSolenoid.set(true);
    }
    public void retractPiston(){
        ejectSolenoid.set(false);
    }
    public void runChooChoo(double speed){
        choochooRight.set(-speed);
        choochooLeft.set(speed);
    }
    public void stopChooChoo(){
        choochooRight.set(0);
        choochooLeft.set(0);
    }
    public boolean getSwitch(){
        return choochooLimitSwitchLeft.get();
    }
    public boolean getSwitch2(){
        return choochooLimitSwitchRight.get();
    }
}
